In [1]:
import sys
sys.path.insert(0,'../')
sys.path

['../',
 'D:\\Thesis\\MachineFairness\\ContexualFairness\\2022-1Spring\\MissingValueDisparity\\notebooks',
 'c:\\python38_64\\python38.zip',
 'c:\\python38_64\\DLLs',
 'c:\\python38_64\\lib',
 'c:\\python38_64',
 '',
 'C:\\Users\\Rakin\\AppData\\Roaming\\Python\\Python38\\site-packages',
 'c:\\python38_64\\lib\\site-packages',
 'c:\\python38_64\\lib\\site-packages\\pgmpy-0.1.15-py3.8.egg',
 'c:\\python38_64\\lib\\site-packages\\win32',
 'c:\\python38_64\\lib\\site-packages\\win32\\lib',
 'c:\\python38_64\\lib\\site-packages\\Pythonwin',
 'c:\\python38_64\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Rakin\\.ipython']

In [2]:
import numpy as np
from utils import *
from datasets.fair_dataset import FairDataset

In [3]:
protected = ["sex"]
privileged_classes = [['Male']]
class_shift = 10
kwargs = {
    'protected_attribute_names': ['sex'],
    'privileged_group': 'Male',
    'favorable_class': 1,
    'classes': [0, 1],
    'sensitive_groups': ['Female', 'Male'],
    'group_shift': 2,
    'alpha': 0.25, 'beta': 1, 'keep_im_prot': True,
    'dist': {'mus': {1: np.array([10, 15]), 
                     0: np.array([10 - class_shift, 15 - class_shift])}, 'sigmas': [3, 3]}
}

In [4]:
estimator = get_estimator('nb', False)
keep_prot = False

In [5]:
def get_performance_summary(train_fd, test_fd, estimator, prediction_func):
    pmod, pmod_results = get_groupwise_performance(train_fd, test_fd,
                                               estimator,
                                               privileged=True,
                                               pos_rate=False)
    umod, umod_results = get_groupwise_performance(train_fd, test_fd,
                                               estimator,
                                               privileged=False,
                                               pos_rate=False)
    mod, mod_results = get_groupwise_performance(train_fd, test_fd,
                                             estimator,
                                             privileged=None,
                                             pos_rate=False)

    p_perf = get_model_performances(pmod, test_fd,
                                prediction_func, keep_prot=keep_prot)
    u_perf = get_model_performances(umod, test_fd,
                                prediction_func, keep_prot=keep_prot)
    m_perf = get_model_performances(mod, test_fd,
                                prediction_func, keep_prot=keep_prot)
    print_table_row(is_header=False, var_value='mean', p_perf=p_perf,
                        u_perf=u_perf, m_perf=m_perf, variable='method')
    return pmod, umod, mod, p_perf, u_perf, m_perf

In [31]:
train_fd, test_fd = get_datasets(
    type='ccd', n_samples=10000, n_features=2,
    train_random_state=47, test_random_state=41,
    **kwargs, method='iterative_imputer.mice')

{'random_seed': 47, 'keep_im_prot': True, 'method': 'iterative_imputer.mice'}
[(array([-2,  3]), [3, 3], 0, 0), (array([0, 5]), [3, 3], 1, 0), (array([ 8, 13]), [3, 3], 0, 1), (array([10, 15]), [3, 3], 1, 1)]
[(array([-2,  3]), [3, 3], 0, 0), (array([0, 5]), [3, 3], 1, 0), (array([ 8, 13]), [3, 3], 0, 1), (array([10, 15]), [3, 3], 1, 1)]
          0         1  sex  label
0 -4.544028  6.917719  0.0    0.0
1  0.772624  4.921235  0.0    0.0
2 -5.164211  8.393282  0.0    0.0
3 -5.038360  5.470870  0.0    0.0
4 -2.883951  1.222588  0.0    0.0
               0          1  sex  label
19995   5.250366  15.866859  1.0    1.0
19996  12.098511  16.791829  1.0    1.0
19997  12.802980  19.425987  1.0    1.0
19998   7.110894  17.730945  1.0    1.0
19999  13.591477  17.545663  1.0    1.0
          0         1  sex  label
0 -4.544028  2.113933  0.0    0.0
1  0.772624  5.675843  0.0    0.0
2 -5.164211  8.393282  0.0    0.0
3 -5.038360  1.782754  0.0    0.0
4 -2.883951  1.222588  0.0    0.0
            

Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.


          0         1  sex  label
0 -2.812137  3.314544  0.0    0.0
1 -1.248417  0.224400  0.0    0.0
2 -0.298569 -0.120541  0.0    0.0
3 -2.461028  5.369555  0.0    0.0
4 -5.678648  0.155979  0.0    0.0
               0          1  sex  label
19995   9.958686  13.915196  1.0    1.0
19996   7.928059  16.617448  1.0    1.0
19997  12.312745  21.622555  1.0    1.0
19998   8.172668  15.303179  1.0    1.0
19999   9.125001  12.919607  1.0    1.0
          0         1  sex  label
0 -2.812137  3.274220  0.0    0.0
1 -1.248417  0.224400  0.0    0.0
2 -0.298569 -0.120541  0.0    0.0
3 -2.461028  3.509447  0.0    0.0
4 -5.678648  1.353792  0.0    0.0
               0          1  sex  label
19995   9.958686  12.454647  1.0    1.0
19996   7.928059  16.617448  1.0    1.0
19997  12.312745  21.622555  1.0    1.0
19998   8.172668  15.303179  1.0    1.0
19999   9.125001  12.919607  1.0    1.0


Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.


In [7]:
complete_df = train_fd.complete_df.astype(float)

In [8]:
train_fd.group_configs

[(array([-2,  3]), [3, 3], 0, 0),
 (array([0, 5]), [3, 3], 1, 0),
 (array([ 8, 13]), [3, 3], 0, 1),
 (array([10, 15]), [3, 3], 1, 1)]

In [9]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(complete_df[complete_df.columns[:-1]], complete_df[complete_df.columns[-1]])
model.theta_

array([[-0.96871471,  3.97595821,  0.5       ],
       [ 9.00431815, 14.05140606,  0.5       ]])

In [10]:
model.sigma_

array([[10.13943171,  9.96107676,  0.25000003],
       [10.06332871, 10.11039807,  0.25000003]])

In [11]:
train_fd.complete_df.head()

0         1  sex  label
0 -4.544028  6.917719  0.0    0.0
1  0.772624  4.921235  0.0    0.0
2 -5.164211  8.393282  0.0    0.0
3 -5.038360  5.470870  0.0    0.0
4 -2.883951  1.222588  0.0    0.0

In [12]:
train_fd.complete_df.tail()

0          1  sex  label
19995   5.250366  15.866859  1.0    1.0
19996  12.098511  16.791829  1.0    1.0
19997  12.802980  19.425987  1.0    1.0
19998   7.110894  17.730945  1.0    1.0
19999  13.591477  17.545663  1.0    1.0

In [13]:
test_fd.complete_df.head()

0         1  sex  label
0 -2.812137  3.314544  0.0    0.0
1 -1.248417  0.224400  0.0    0.0
2 -0.298569 -0.120541  0.0    0.0
3 -2.461028  5.369555  0.0    0.0
4 -5.678648  0.155979  0.0    0.0

In [14]:
test_fd.complete_df.tail()

0          1  sex  label
19995   9.958686  13.915196  1.0    1.0
19996   7.928059  16.617448  1.0    1.0
19997  12.312745  21.622555  1.0    1.0
19998   8.172668  15.303179  1.0    1.0
19999   9.125001  12.919607  1.0    1.0

In [15]:
baseline_fd = FairDataset(df=complete_df, protected_attribute_names=['sex'])

In [16]:
for s in [0, 1]:
    for l in [0, 1]:
        print('s', s, 'label', l)
        print(complete_df[(complete_df['sex'] == s) & (complete_df['label'] == l)].describe())

s 0 label 0
                 0            1     sex   label
count  7500.000000  7500.000000  7500.0  7500.0
mean     -1.971826     2.964759     0.0     0.0
std       3.009595     2.975627     0.0     0.0
min     -14.679162    -8.693075     0.0     0.0
25%      -3.999826     0.925972     0.0     0.0
50%      -1.976793     2.953405     0.0     0.0
75%       0.059479     4.936042     0.0     0.0
max      10.733290    13.507203     0.0     0.0
s 0 label 1
                 0            1     sex   label
count  2500.000000  2500.000000  2500.0  2500.0
mean      7.961709    13.079534     0.0     1.0
std       3.006858     3.027690     0.0     0.0
min      -2.027707     2.781380     0.0     1.0
25%       5.977845    11.013145     0.0     1.0
50%       7.915225    13.133695     0.0     1.0
75%       9.966237    15.077240     0.0     1.0
max      17.600777    24.220583     0.0     1.0
s 1 label 0
                 0            1     sex   label
count  7500.000000  7500.000000  7500.0  7500.0
mean

In [17]:
incomplete_df = train_fd.get_incomplete_df()
for s in [0, 1]:
    for l in [0, 1]:
        print('s', s, 'label', l)
        print(incomplete_df[(incomplete_df['sex'] == s) & (incomplete_df['label'] == l)].describe())

s 0 label 0
                 0            1     sex   label
count  7500.000000  4507.000000  7500.0  7500.0
mean     -1.971826     2.973859     0.0     0.0
std       3.009595     2.974248     0.0     0.0
min     -14.679162    -6.482708     0.0     0.0
25%      -3.999826     0.913326     0.0     0.0
50%      -1.976793     2.945779     0.0     0.0
75%       0.059479     4.957119     0.0     0.0
max      10.733290    13.207772     0.0     0.0
s 0 label 1
                 0            1     sex   label
count  2500.000000  1493.000000  2500.0  2500.0
mean      7.961709    13.056682     0.0     1.0
std       3.006858     3.097647     0.0     0.0
min      -2.027707     2.908823     0.0     1.0
25%       5.977845    10.942813     0.0     1.0
50%       7.915225    13.134066     0.0     1.0
75%       9.966237    15.183945     0.0     1.0
max      17.600777    24.220583     0.0     1.0
s 1 label 0
                 0            1     sex   label
count  7500.000000  6762.000000  7500.0  7500.0
mean

In [18]:
train_fd.get_incomplete_df()

0          1  sex  label
0      -4.544028        NaN  0.0    0.0
1       0.772624        NaN  0.0    0.0
2      -5.164211   8.393282  0.0    0.0
3      -5.038360        NaN  0.0    0.0
4      -2.883951   1.222588  0.0    0.0
...          ...        ...  ...    ...
19995   5.250366  15.866859  1.0    1.0
19996  12.098511  16.791829  1.0    1.0
19997  12.802980  19.425987  1.0    1.0
19998   7.110894        NaN  1.0    1.0
19999  13.591477  17.545663  1.0    1.0

[20000 rows x 4 columns]

In [19]:
train_fd.imputed_df

0          1  sex  label
0      -4.544028   2.113933  0.0    0.0
1       0.772624   5.675843  0.0    0.0
2      -5.164211   8.393282  0.0    0.0
3      -5.038360   1.782754  0.0    0.0
4      -2.883951   1.222588  0.0    0.0
...          ...        ...  ...    ...
19995   5.250366  15.866859  1.0    1.0
19996  12.098511  16.791829  1.0    1.0
19997  12.802980  19.425987  1.0    1.0
19998   7.110894  10.546759  1.0    1.0
19999  13.591477  17.545663  1.0    1.0

[20000 rows x 4 columns]

In [20]:
train_fd.imputer.imputation_sequence_[0].estimator.intercept_

5.158220939005139

In [21]:
test_fd.imputer

IterativeImputer(estimator=LinearRegression(), imputation_order='descending',
                 max_iter=5, random_state=0)

In [22]:
train_fd.get_incomplete_df()['1'].count()

15000

In [32]:
print_table_row(is_header=True, variable='Method')
# output = get_performance_summary(baseline_fd, baseline_fd, estimator, get_predictions)
output = get_performance_summary(train_fd, train_fd, estimator, get_predictions)

Method	 & 	AC_p	 & 	AC_u	 & 	SR_p	 & 	SR_u	 & 	FPR_p	 & 	FPR_u
mean	 & 	98.9	 & 	97.8	 & 	26.4	 & 	23.1	 & 	02.1	 & 	00.5


In [24]:
pmod, umod, mod, _, _, _ = output

In [25]:
pmod.theta_

array([[ 0.03439641,  5.05969836],
       [10.04692702, 14.75217504]])

In [26]:
pmod.sigma_

array([[9.2099444 , 8.60846329],
       [8.91501002, 9.06500865]])

In [27]:
umod.theta_

array([[-1.97182582,  3.31958762],
       [ 7.96170928, 12.04500091]])

In [28]:
umod.sigma_

array([[9.05645519, 7.1025452 ],
       [9.03758089, 8.87262979]])

In [29]:
mod.theta_

array([[-0.96871471,  4.18964299],
       [ 9.00431815, 13.39858797]])

In [30]:
mod.sigma_

array([[10.13943171,  8.61250059],
       [10.06332871, 10.80101717]])